server:
  port: 9191

spring:
  application:
    name: API-GATWAY
  cloud:
    gateway:
      discovery:
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: GESTION-SERVICE
        uri: lb://GESTION-SERVICE
        predicates:
        - Path=/immobilier/**
      - id: GESTION-SERVICE
        uri: lb://GESTION-SERVICE
        predicates:
        - Path=/transaction/**
      - id: CONTRACT-SERVICE
        uri: lb://CONTRACT-SERVICE
        predicates:
        - Path=/contract/**



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
   